# Python'ı baz alarak bir Docker image'ı oluşturuyoruz
FROM python:3.9-slim

# Çalışma dizinini belirleyelim
WORKDIR /app

# Gereksinimlerinizi kopyalayın ve yükleyin
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Wait-for-it scriptini ve uygulamanızı kopyalayın
COPY wait-for-it.sh /app/
COPY . /app/

# Wait-for-it scriptine çalıştırma izni verin
RUN chmod +x /app/wait-for-it.sh

# Uygulamanızı başlatmadan önce DB hazır olana kadar bekle
CMD ./wait-for-it.sh db:5432 -- python app.py
